export declare const backend: import("@aws-amplify/backend").Backend<{
    patientsFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    medicsFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    examsFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    reservationsFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    chatFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    agentIntegrationFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    icd10Function: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    documentUploadFunction: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/plugin-types").FunctionResources> & import("@aws-amplify/plugin-types").ResourceAccessAcceptorFactory & import("@aws-amplify/backend-function").AddEnvironmentFactory & import("@aws-amplify/plugin-types").StackProvider>;
    storage: import("@aws-amplify/plugin-types").ConstructFactory<import("@aws-amplify/plugin-types").ResourceProvider<import("@aws-amplify/backend-storage").StorageResources> & import("@aws-amplify/plugin-types").StackProvider>;
}>;
