import { Amplify } from 'aws-amplify';
import { getAmplifyApiConfig } from './config/api-config';

// Import Amplify outputs (generated after backend deployment)
let amplifyOutputs: any = {};

try {
  // This will be generated by Amplify after backend deployment
  amplifyOutputs = await import('./amplify_outputs.json');
} catch (error) {
  console.warn('amplify_outputs.json not found, using environment configuration');
}

export function configureAmplify() {
  try {
    // Merge Amplify outputs with custom REST API configuration
    const config = {
      ...amplifyOutputs,
      ...getAmplifyApiConfig(),
    };

    Amplify.configure(config);
    console.log('Amplify configured successfully with external REST API');
  } catch (error) {
    console.error('Error configuring Amplify:', error);
  }
}

export default amplifyOutputs;
